[project]
authors = ["Erik Tollerud <erik.tollerud@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "structparams_inference_biases"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.1.1,<3"
scipy = ">=1.14.1,<2"
matplotlib = ">=3.9.2,<4"
jupyterlab = ">=4.2.5,<5"
dynesty = ">=2.1.4,<3"
emcee = ">=3.1.6,<4"
corner = ">=2.2.2,<3"
astropy = ">=6.1.3,<7"
tqdm = ">=4.66.5,<5"
ipywidgets = ">=8.1.5,<9"
sympy = ">=1.13.2,<2"
regions = ">=0.9,<0.10"
photutils = ">=1.13.0,<2"
python = "3.12.*"
pip = ">=24.2,<25"
